services:
  - type: web
    name: alerts-app
    runtime: node
    buildCommand: npm install && cd client && npm install && npm run build && cd ../server && npm install
    startCommand: cd server && node index.js
    envVars:
      - key: NODE_ENV
        value: production
